/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package resturentmanagement;

import java.awt.Color;
import java.awt.Font;
import java.awt.print.PrinterException;
import java.text.MessageFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author HOME
 */
public class BILL extends javax.swing.JFrame {

    /**
     * Creates new form BILL
     */
    ORDER order=new ORDER();
    
    public BILL() {
        initComponents();
        
        //transpaternt the text fields
        jTextField1.setBackground(new java.awt.Color(0,0,0,1));
        jTextField2.setBackground(new java.awt.Color(0,0,0,1));
        jTextField3.setBackground(new java.awt.Color(0,0,0,1));
        jTextFieldDate.setBackground(new java.awt.Color(0,0,0,1));
 
        currentdate();// call to date function
       order.filloderTable(jTable1); 
        jTextField1.setEditable(false);//disable total bill textfield
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldDate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 0, 153));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 153, 0));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("BILL PRINT");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(277, 21, 142, 29);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\hasa\\Downloads\\unnamed.jpg")); // NOI18N
        jPanel2.add(jLabel8);
        jLabel8.setBounds(0, 0, 760, 80);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 757, 0);

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Table No", "Name", "Price"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setSelectionBackground(new java.awt.Color(0, 204, 255));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(372, 98, 375, 152);

        jTextArea.setColumns(20);
        jTextArea.setRows(5);
        jScrollPane2.setViewportView(jTextArea);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(372, 290, 375, 193);

        jTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jTextField1.setOpaque(false);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(150, 250, 102, 16);

        jLabel2.setText("Total Bill :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(95, 253, 46, 14);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "T1", "T2", "T3", "T4", "T5", "T6", "T7", "T8", "T9", "T10" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(72, 144, 80, 34);

        jLabel3.setText("Select Table No :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(47, 112, 81, 14);

        jTextField2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jTextField2.setOpaque(false);
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(151, 290, 102, 16);

        jLabel4.setText("Enter Pay Amount :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(47, 290, 94, 14);

        jTextField3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jTextField3.setOpaque(false);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(151, 324, 102, 16);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/button.png"))); // NOI18N
        jButton2.setText("genarate BILL");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(110, 370, 110, 40);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/button.png"))); // NOI18N
        jButton3.setText("CLEAR BILL");
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(240, 370, 100, 40);

        jLabel5.setText("Balance :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(97, 324, 44, 14);

        jTextFieldDate.setBackground(new java.awt.Color(153, 0, 153));
        jTextFieldDate.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jTextFieldDate.setOpaque(false);
        jPanel1.add(jTextFieldDate);
        jTextFieldDate.setBounds(252, 87, 102, 16);

        jLabel6.setText("Date :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(208, 87, 40, 14);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/button.png"))); // NOI18N
        jButton1.setText("PRINT BILL");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(160, 420, 110, 50);

        jPanel3.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 0, 204));
        jLabel10.setText("BILL");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(310, 20, 60, 40);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/titleback2.jpg"))); // NOI18N
        jPanel3.add(jLabel9);
        jLabel9.setBounds(0, 0, 760, 80);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 0, 760, 80);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Background.jpg"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(0, 0, 760, 520);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 756, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(772, 551));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void currentdate(){
    
    Calendar cal =new GregorianCalendar();
    int month=cal.get(Calendar.MONTH);
    int year =cal.get(Calendar.YEAR);
    int day= cal.get(Calendar.DAY_OF_MONTH);
    jTextFieldDate.setText(year+"/"+(month+1)+"/"+day);
    jTextFieldDate.setEditable(false);
    }
    
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    String value1 =jComboBox1.getSelectedItem().toString();
        
    DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
    TableRowSorter<DefaultTableModel> tro=new TableRowSorter<DefaultTableModel>(model);
    jTable1.setRowSorter(tro);
    tro.setRowFilter(RowFilter.regexFilter(value1));

      //continuosly add total price (Total price)
     int rowcount=jTable1.getRowCount();
     int sum=0;
     
     for(int i=0; i<rowcount; i++)
     {
     sum+=Integer.parseInt(jTable1.getValueAt(i, 2).toString());
     }
     jTextField1.setText(Integer.toString(sum));
     
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

     
        
        jTextArea.setText("#################################################\n");
        jTextArea.setText(jTextArea.getText()+"\t        Bill  Receipt           \t\n");
        jTextArea.setText(jTextArea.getText()+"#################################################\n");
        jTextArea.setText(jTextArea.getText()+"Odered Foods::....................................\tDate : "+jTextFieldDate.getText()+"\n\n");
          int b=0;
          String c;
        for(int y=0; y<jTable1.getRowCount(); y++){
            c=(jTable1.getValueAt(y, 1).toString());
            b=Integer.parseInt(jTable1.getValueAt(y,2).toString()); 
            jTextArea.setText(jTextArea.getText()+"\t  "+c+": "+b+"\n");
        }
         jTextArea.setText(jTextArea.getText()+"\t..................................\n");
        jTextArea.setText(jTextArea.getText()+"\t        Total Bill :"+jTextField1.getText()+"\n");
        jTextArea.setText(jTextArea.getText()+"\t\n");
        jTextArea.setText(jTextArea.getText()+"\tPayed Amount :"+jTextField2.getText()+"\n\n");
        
        jTextArea.setText(jTextArea.getText()+"\t..................................\n");
        jTextArea.setText(jTextArea.getText()+"\t Balance :"+jTextField3.getText()+"\n\n"); 
        jTextArea.setText(jTextArea.getText()+"thank you!\n");
        


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         
//delete select data

        String id=jComboBox1.getSelectedItem().toString();
         try{
                
            if(order.removeorder(id))// pass values to employee.java
               {
                JOptionPane.showMessageDialog(rootPane, "Bill cleared Successfuly!!","Remove Bill", JOptionPane.INFORMATION_MESSAGE);
               }
            else{
                JOptionPane.showMessageDialog(rootPane, "Bill cleared Failed!!","Remove Bill Error", JOptionPane.ERROR_MESSAGE);
                }  
            
            }
            catch(NumberFormatException ex)
            {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage()+"Enter Table No", "Table No ERROR", JOptionPane.ERROR_MESSAGE);
            }
       
               jTextArea.setText("");//clear text area

        //clear te table to refresh
         jTable1.setModel(new DefaultTableModel(null,new Object[]{"Table No","Name","Price"}));

        //populate table
       // order.filloderTable(jTable1); 
        
        jComboBox1.setSelectedIndex(0);//selected combox value to default(reset)
        
        jTextField1.setText("");//clear fields
        jTextField2.setText("");
        jTextField3.setText("");
        
        order.filloderTable(jTable1);
               
               
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased
        // TODO add your handling code here:
        int v=0;
        v = Integer.parseInt(jTextField2.getText().toString())- Integer.parseInt(jTextField1.getText().toString());
        jTextField3.setText(v+".00");
        jTextField3.setEditable(false);
        jTextField1.setEditable(false);            
        
  
    }//GEN-LAST:event_jTextField2KeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            Boolean ppt= jTextArea.print();
        } catch (PrinterException ex) {
            Logger.getLogger(BILL.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BILL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BILL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BILL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BILL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BILL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextFieldDate;
    // End of variables declaration//GEN-END:variables
}
