/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package resturentmanagement;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HOME
 */
public class ManageEmployeeForm extends javax.swing.JFrame {

    /**
     * Creates new form ManageEmployeeForm
     */
    
    EMPLOYEE employee=new EMPLOYEE();
    
    public ManageEmployeeForm() {
        initComponents();
        jTextFieldID.setBackground(new java.awt.Color(0,0,0,1));
        jTextFieldFNAME.setBackground(new java.awt.Color(0,0,0,1));
        jTextFieldPHONE.setBackground(new java.awt.Color(0,0,0,1));
        jTextFieldEMAIL.setBackground(new java.awt.Color(0,0,0,1));
        employee.fillEmployeeTable(jTable1);//populate the jtable
        
    }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanelback = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldFNAME = new javax.swing.JTextField();
        jTextFieldPHONE = new javax.swing.JTextField();
        jTextFieldID = new javax.swing.JTextField();
        jTextFieldEMAIL = new javax.swing.JTextField();
        jButtonADD = new javax.swing.JButton();
        jButtonEDITE = new javax.swing.JButton();
        jButtonREMOVE = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jRadioButtonMale = new javax.swing.JRadioButton();
        jRadioButtonFemale = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanelback.setPreferredSize(new java.awt.Dimension(1200, 800));
        jPanelback.setLayout(null);

        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 204));
        jLabel1.setText("EMPLOYEE MANAGE");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(207, 26, 258, 33);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/titleback1.jpg"))); // NOI18N
        jPanel2.add(jLabel9);
        jLabel9.setBounds(0, 0, 800, 80);

        jPanelback.add(jPanel2);
        jPanel2.setBounds(0, 0, 810, 80);

        jLabel2.setText("ID :");
        jPanelback.add(jLabel2);
        jLabel2.setBounds(27, 129, 18, 14);

        jLabel3.setText("Name :");
        jPanelback.add(jLabel3);
        jLabel3.setBounds(27, 156, 34, 14);

        jLabel5.setText("Phone No :");
        jPanelback.add(jLabel5);
        jLabel5.setBounds(27, 231, 53, 14);

        jLabel6.setText("Email :");
        jPanelback.add(jLabel6);
        jLabel6.setBounds(27, 258, 31, 14);

        jTextFieldFNAME.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jTextFieldFNAME.setOpaque(false);
        jPanelback.add(jTextFieldFNAME);
        jTextFieldFNAME.setBounds(106, 156, 117, 16);

        jTextFieldPHONE.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jTextFieldPHONE.setOpaque(false);
        jPanelback.add(jTextFieldPHONE);
        jTextFieldPHONE.setBounds(106, 231, 117, 16);

        jTextFieldID.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldID.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jTextFieldID.setCaretColor(new java.awt.Color(0, 204, 204));
        jTextFieldID.setOpaque(false);
        jPanelback.add(jTextFieldID);
        jTextFieldID.setBounds(106, 129, 117, 16);

        jTextFieldEMAIL.setBackground(new java.awt.Color(255, 102, 0));
        jTextFieldEMAIL.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jTextFieldEMAIL.setOpaque(false);
        jPanelback.add(jTextFieldEMAIL);
        jTextFieldEMAIL.setBounds(106, 258, 117, 16);

        jButtonADD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/button.png"))); // NOI18N
        jButtonADD.setText("ADD");
        jButtonADD.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonADDActionPerformed(evt);
            }
        });
        jPanelback.add(jButtonADD);
        jButtonADD.setBounds(10, 310, 110, 40);

        jButtonEDITE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/button.png"))); // NOI18N
        jButtonEDITE.setText("EDITE");
        jButtonEDITE.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonEDITE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEDITEActionPerformed(evt);
            }
        });
        jPanelback.add(jButtonEDITE);
        jButtonEDITE.setBounds(130, 310, 100, 40);

        jButtonREMOVE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/button.png"))); // NOI18N
        jButtonREMOVE.setText("REMOVE");
        jButtonREMOVE.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonREMOVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonREMOVEActionPerformed(evt);
            }
        });
        jPanelback.add(jButtonREMOVE);
        jButtonREMOVE.setBounds(10, 360, 110, 40);

        jLabel7.setText("Status :");
        jPanelback.add(jLabel7);
        jLabel7.setBounds(27, 106, 38, 14);

        jComboBox1.setBackground(new java.awt.Color(204, 204, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "manager", "cheff", "waiter", "cashier" }));
        jPanelback.add(jComboBox1);
        jComboBox1.setBounds(106, 103, 117, 20);

        jRadioButtonMale.setBackground(new java.awt.Color(255, 102, 0));
        buttonGroup1.add(jRadioButtonMale);
        jRadioButtonMale.setText("Male");
        jRadioButtonMale.setOpaque(false);
        jPanelback.add(jRadioButtonMale);
        jRadioButtonMale.setBounds(110, 190, 47, 23);

        jRadioButtonFemale.setBackground(new java.awt.Color(255, 102, 0));
        buttonGroup1.add(jRadioButtonFemale);
        jRadioButtonFemale.setText("Female");
        jRadioButtonFemale.setOpaque(false);
        jRadioButtonFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFemaleActionPerformed(evt);
            }
        });
        jPanelback.add(jRadioButtonFemale);
        jRadioButtonFemale.setBounds(164, 190, 59, 23);

        jLabel8.setText("Gender");
        jPanelback.add(jLabel8);
        jLabel8.setBounds(27, 194, 35, 14);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Status", "Name", "Gender", "Phon No", "Email"
            }
        ));
        jTable1.setSelectionBackground(new java.awt.Color(0, 204, 255));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanelback.add(jScrollPane2);
        jScrollPane2.setBounds(240, 100, 498, 187);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/button.png"))); // NOI18N
        jButton1.setText("clear fields");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanelback.add(jButton1);
        jButton1.setBounds(130, 360, 100, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Background.jpg"))); // NOI18N
        jPanelback.add(jLabel4);
        jLabel4.setBounds(0, 80, 810, 430);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelback, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelback, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(816, 540));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonADDActionPerformed
        // TODO add your handling code here:
        
        String id=jTextFieldID.getText();
        String status=jComboBox1.getSelectedItem().toString();
        String fname =jTextFieldFNAME.getText();
        String gender="";
        String phone =jTextFieldPHONE.getText();
        String email =jTextFieldEMAIL.getText();
        
        if(jRadioButtonMale.isSelected()){
            gender="Male";
        }else if(jRadioButtonFemale.isSelected()){
            gender="Female";
        }
        
        if(fname.trim().equals("") ||status.trim().equals("") || gender.equals("") || phone.trim().equals("") )
        {
          JOptionPane.showMessageDialog(rootPane, "Fields are empty!!","EMPTY", JOptionPane.ERROR_MESSAGE);   
        }
        else{
                    
             if(employee.addEmployee(id, status, fname, gender, phone, email))// pass values to employee
                 {
                 JOptionPane.showMessageDialog(rootPane, "Employee added Successfuly!!","ADD EMPLOYEE", JOptionPane.INFORMATION_MESSAGE);
                 }
             else{
                 JOptionPane.showMessageDialog(rootPane, "Employee added Failed!!","ADD EMPLOYEE", JOptionPane.ERROR_MESSAGE);
                }  
        }
        jTextFieldID.setText("");
        jTextFieldFNAME.setText("");
        jComboBox1.setSelectedIndex(0);
        jTextFieldPHONE.setText("");
        jTextFieldEMAIL.setText("");
        
        jTable1.setModel(new DefaultTableModel(null,new Object[]{"ID","First Name","Last Name","Gender", "Phone","Email"}));
        //populate table
        employee.fillEmployeeTable(jTable1);
    }//GEN-LAST:event_jButtonADDActionPerformed

    private void jButtonEDITEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEDITEActionPerformed
        
        // edite selected employee
        //get dta from text fields
        int id=0;
        String fname =jTextFieldFNAME.getText();
        String gender ="";
        String phone =jTextFieldPHONE.getText();
        String email =jTextFieldEMAIL.getText();
        String status=jComboBox1.getSelectedItem().toString();
        
        if(jRadioButtonMale.isSelected()){
            gender="Male";
        }else if(jRadioButtonFemale.isSelected()){
            gender="Female";
        }
        
        if(fname.trim().equals("") || gender.trim().equals("") || phone.trim().equals("") )
        {
          JOptionPane.showMessageDialog(rootPane, "Fields are empty!!","EMPTY", JOptionPane.ERROR_MESSAGE);   
        }
        else{
              
            try{
            id= Integer.valueOf(jTextFieldID.getText()); 
                
            if(employee.editEmployee(id, status, fname, gender, phone, email))// pass values to employee
               {
                JOptionPane.showMessageDialog(rootPane, "Employee Updated Successfuly!!","EDIT EMPLOYEE", JOptionPane.INFORMATION_MESSAGE);
               }
            else{
                JOptionPane.showMessageDialog(rootPane, "Employee Updated Failed!!","EDIT EMPLOYEE", JOptionPane.ERROR_MESSAGE);
                }  
            
            }
            catch(NumberFormatException ex)
            {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage()+"Enter Employee ID", "EMPLOYEE ID ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
        jTextFieldID.setText("");
        jTextFieldFNAME.setText("");
        jComboBox1.setSelectedIndex(0);
        jTextFieldPHONE.setText("");
        jTextFieldEMAIL.setText("");
        
        jTable1.setModel(new DefaultTableModel(null,new Object[]{"ID","First Name","Last Name","Gender", "Phone","Email"}));
        //populate table
        employee.fillEmployeeTable(jTable1);
        
    }//GEN-LAST:event_jButtonEDITEActionPerformed

    private void jButtonREMOVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonREMOVEActionPerformed
        // TODO add your handling code here:
        //delete select data
         try{
           int id= Integer.valueOf(jTextFieldID.getText()); 
                
            if(employee.removeEmployee(id))// pass values to employee.java
               {
                JOptionPane.showMessageDialog(rootPane, "Employee Deleted Successfuly!!","Remove EMPLOYEE", JOptionPane.INFORMATION_MESSAGE);
               }
            else{
                JOptionPane.showMessageDialog(rootPane, "Employee Data Delete Failed!!","Remove Employee Error", JOptionPane.ERROR_MESSAGE);
                }  
            
            }
            catch(NumberFormatException ex)
            {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage()+"Enter Employee ID", "EMPLOYEE ID ERROR", JOptionPane.ERROR_MESSAGE);
            }
         jTextFieldID.setText("");
        jTextFieldFNAME.setText("");
        jComboBox1.setSelectedIndex(0);
        jTextFieldPHONE.setText("");
        jTextFieldEMAIL.setText("");
        
        jTable1.setModel(new DefaultTableModel(null,new Object[]{"ID","First Name","Last Name","Gender", "Phone","Email"}));
        //populate table
        employee.fillEmployeeTable(jTable1);
        
    }//GEN-LAST:event_jButtonREMOVEActionPerformed

    private void jRadioButtonFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonFemaleActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        
        DefaultTableModel  model = (DefaultTableModel)jTable1.getModel();
      
        int rIndex = jTable1.getSelectedRow();//get the select row index

        String gender= model.getValueAt(rIndex, 3).toString();
        if(gender.equals("Male")){//get value from table to jRadioButtons
            jRadioButtonMale.setSelected(true);
        }else if(gender.equals("Female")){
            jRadioButtonFemale.setSelected(true);
        }
        //get value from table to jComboBox
        String status=model.getValueAt(rIndex, 1).toString();
        for(int i=0; i<jComboBox1.getItemCount(); i++)
        {
            if(jComboBox1.getItemAt(i).toString().equalsIgnoreCase(status))
            {
                jComboBox1.setSelectedIndex(i);
            }
        }
        //get value from table to textfields
        
        jTextFieldID.setText(model.getValueAt(rIndex,0).toString());
        jTextFieldFNAME.setText(model.getValueAt(rIndex,2).toString());
       
        jTextFieldPHONE.setText(model.getValueAt(rIndex,4).toString());
        jTextFieldEMAIL.setText(model.getValueAt(rIndex,5).toString());
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jComboBox1.setSelectedIndex(0);
        jTextFieldID.setText("");
        jTextFieldFNAME.setText("");
        jTextFieldPHONE.setText("");
        jTextFieldEMAIL.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageEmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageEmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageEmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageEmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageEmployeeForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonADD;
    private javax.swing.JButton jButtonEDITE;
    private javax.swing.JButton jButtonREMOVE;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelback;
    private javax.swing.JRadioButton jRadioButtonFemale;
    private javax.swing.JRadioButton jRadioButtonMale;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldEMAIL;
    private javax.swing.JTextField jTextFieldFNAME;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldPHONE;
    // End of variables declaration//GEN-END:variables
}
